### ISSUE TITLE
Error loading Cartiqo NL styles

### ISSUE THREAD

**Issue by emacgillavry** [maptiler/qgis-maptiler-plugin#104]
Loading the Cartiqo NL styles, we're experiencing the stack trace below. Loading the tiles directly is no problem.

```
 WARNING    Traceback (most recent call last):
              File "/home/edward/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/browser_mapitem.py", line 48, in handleDoubleClick
              self._add_vector_to_canvas()
              File "/home/edward/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/browser_mapitem.py", line 195, in _add_vector_to_canvas
              style_json_data, node_map, attribution_text)
              File "/home/edward/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/browser_mapitem.py", line 223, in _add_vtlayer_from_style_json
              source_id, style_json_data)
              File "/home/edward/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/converter.py", line 101, in get_renderer_labeling
              renderer, labeling = parse_layers(source_layers, style_json_data.get('id'))
              File "/home/edward/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 790, in parse_layers
              st = parse_line_layer(json_layer, style_name)
              File "/home/edward/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 536, in parse_line_layer
              json_line_width, PropertyType.Line, PX_RATIO)
              File "/home/edward/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 212, in parse_interpolate_list_by_zoom
              expr = parse_interpolate_by_zoom(d, multiplier)
              File "/home/edward/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 231, in parse_interpolate_by_zoom
              scale_expr = parse_stops(base, stops, multiplier)
              File "/home/edward/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 260, in parse_stops
              interval_str = f"WHEN @zoom_level > {bz} AND @zoom_level               File "/home/edward/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 314, in interpolate_exp
              return f"{value_min} + {value_max - value_min} * " \
             TypeError: unsupported operand type(s) for -: 'list' and 'list'
```
As it happens, it's `gl2qgis.py` on line 314...

**Comment by klokan** [comment]
@lazaa32 - can there be a hotfix done for the next release, please?

**Comment by emacgillavry** [comment]
Confirming same stack trace happening when loading Cartiqo in QGIS 3.14 on Windows 10 using the Maptile plugin.

**Comment by lazaa32** [comment]
Thank you for reporting the issue. There is a bug while parsing interpolation function that uses an expression with `match` operator. Hot-fix will be released in few days.

**Comment by emacgillavry** [comment]
Kudos for the quick assessment! looking forward to the release :-)

**Comment by lazaa32** [comment]
As mentioned in #103 QGIS does not support nested expression. In case of Cartiqo style it means QGIS cannot parse interpolation function with `match` operator (see below).
I will make a fix so there is no error message but properties that use similar interpolation function will be set to constant default value and will not change on zooms.
```
[
          "interpolate",
          [
            "exponential",
            1.2
          ],
          [
            "zoom"
          ],
          8,
          [
            "match",
            [
              "get",
              "type"
            ],
            "motorway",
            0,
            "main",
            0,
            0
          ],
          9,
          [
            "match",
            [
              "get",
              "type"
            ],
            "motorway",
            0.5,
            "main",
            0,
            0
          ],
          10,
          [
            "match",
            [
              "get",
              "type"
            ],
            "local",
            0,
            "secondary",
            0,
            "motorway",
            1.3,
            "main",
            0.6,
            0
          ],
          11,
          [
            "match",
            [
              "get",
              "type"
            ],
            "motorway",
            1.3,
            "main",
            0.5,
            0
          ],
          20,
          [
            "match",
            [
              "get",
              "type"
            ],
            "motorway",
            18,
            "main",
            16,
            0
          ]
        ]
```
