### ISSUE TITLE
Error on intial load: ImportError: /usr/lib/libc.so: invalid ELF header 

### ISSUE THREAD

**Issue by tabell** [maptiler/qgis-maptiler-plugin#121]
Latest QGIS on Arch Linux, installation seems to succeed but loading the plugin immediately fails with this cryptic error.

Couldn't load plugin 'qgis-maptiler-plugin' due to an error when calling its classFactory() method 

ImportError: /usr/lib/libc.so: invalid ELF header 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/__init__.py", line 35, in classFactory
    from .maptiler import MapTiler
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/maptiler.py", line 34, in 
    from .browser_root_collection import DataItemProvider
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/browser_root_collection.py", line 7, in 
    from .browser_mapitem import MapDataItem
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/browser_mapitem.py", line 11, in 
    from .gl2qgis import converter
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/converter.py", line 19, in 
    from PIL import Image
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alex/.local/lib/python3.8/site-packages/PIL/Image.py", line 69, in 
    from . import _imaging as core
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: /usr/lib/libc.so: invalid ELF header

Python version: 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0] 
QGIS version: 3.14.0-Pi Pi, exported 

Python Path:
/usr/share/qgis/python
/home/alex/.local/share/QGIS/QGIS3/profiles/default/python
/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/alex/.local/lib/python3.8/site-packages
/usr/lib/python3.8/site-packages
/home/alex/.local/share/QGIS/QGIS3/profiles/default/python

**Comment by tabell** [comment]
This does not seem to be reproducible on other systems, sorry for noise.
