### ISSUE TITLE
Unable to use own style

### ISSUE THREAD

**Issue by zstadler** [maptiler/qgis-maptiler-plugin#142]
- Installed plugin version 1.1.3 using the QGIS plugin manager.
- Added my MapTiler key.
- Added the [Israel Hiking Map](https://israelhiking.osm.org.il) as a vector map using [its Style URL](https://raw.githubusercontent.com/IsraelHikingMap/VectorMap/master/Styles/IHM.json) 
![image](https://user-images.githubusercontent.com/1304610/101748539-5ac16180-3ad5-11eb-8e38-9623eb4e5f1b.png)
- It fails with an error.   
```
   2020-12-10T10:40:36     WARNING    Traceback (most recent call last):
              File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-maptiler-plugin\browser_mapitem.py", line 46, in handleDoubleClick
              self._add_custom_to_canvas()
              File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-maptiler-plugin\browser_mapitem.py", line 336, in _add_custom_to_canvas
              if self._is_vector_json(json_url):
              File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-maptiler-plugin\browser_mapitem.py", line 119, in _is_vector_json
              data_format = json_data['format']
             KeyError: 'format'
```

How can I help investigating this?

**Comment by lazaa32** [comment]
Hi @zstadler, it looks we have a nice bug here, thanks. Plugin expects that style JSON has a specific name `style.json`. I tried to rename your style json and it works. Map gets loaded but another error occurs:
```
Traceback (most recent call last):
  File "/home/adam/.local/share/QGIS/QGIS3/profiles/SOTM/python/plugins/qgis-maptiler-plugin/browser_mapitem.py", line 46, in handleDoubleClick
    self._add_custom_to_canvas()
  File "/home/adam/.local/share/QGIS/QGIS3/profiles/SOTM/python/plugins/qgis-maptiler-plugin/browser_mapitem.py", line 338, in _add_custom_to_canvas
    self._add_vector_to_canvas(data_key='custom')
  File "/home/adam/.local/share/QGIS/QGIS3/profiles/SOTM/python/plugins/qgis-maptiler-plugin/browser_mapitem.py", line 194, in _add_vector_to_canvas
    self._add_vtlayer_from_style_json(
  File "/home/adam/.local/share/QGIS/QGIS3/profiles/SOTM/python/plugins/qgis-maptiler-plugin/browser_mapitem.py", line 222, in _add_vtlayer_from_style_json
    renderer, labeling = converter.get_renderer_labeling(
  File "/home/adam/.local/share/QGIS/QGIS3/profiles/SOTM/python/plugins/qgis-maptiler-plugin/gl2qgis/converter.py", line 105, in get_renderer_labeling
    renderer, labeling = parse_layers(source_layers, style_json_data.get('id'))
  File "/home/adam/.local/share/QGIS/QGIS3/profiles/SOTM/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 848, in parse_layers
    st = parse_line_layer(json_layer, style_name)
  File "/home/adam/.local/share/QGIS/QGIS3/profiles/SOTM/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 577, in parse_line_layer
    line_color = parse_color(json_line_color)
  File "/home/adam/.local/share/QGIS/QGIS3/profiles/SOTM/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 70, in parse_color
    raise ValueError("unknown color syntax", json_color)
ValueError: ('unknown color syntax', 'orange')
```
Plugin can't read colors defined with keywords. It can read only colors defined with the RGB cubic-coordinate system (via the #-hexadecimal or the rgb() and rgba() functional notations) or with the HSL cylindrical-coordinate system (via the hsl() and hsla() functional notations).

I will include these two bugfixes in next release until then please avoid keyword color definition and use `style.json` as a name for styl JSON.

**Comment by zstadler** [comment]
Hi @lazaa32,
Thanks for the quick response! I'll be looking forward to the next release.
