### ISSUE TITLE
Error for `validate_credentials`

### ISSUE THREAD

**Issue by jd-foster** [maptiler/qgis-maptiler-plugin#170]
<html><head></head><body>

Installed version | 3.0.2
-- | --
Available version (stable) | 3.0.2 updated at Mon Feb 28 04:02:34 2022
On MacOS, QGIS 3.24.

</body></html>

Error returned in QGIS console on using the geocoding API search box:
```
2022-03-24T15:05:29     WARNING    Traceback (most recent call last):
              File "/Users/xx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/geocoder.py", line 78, in on_searchword_returned
              geojson_dict = self._fetch_geocoding_api(searchword)
              File "/Users/xx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/geocoder.py", line 118, in _fetch_geocoding_api
              geojson_dict = geocoder.geocoding(searchword, center_lonlat)
              File "/Users/xx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/geocoder.py", line 21, in geocoding
              if not utils.validate_credentials(auth_cfg_id):
             TypeError: validate_credentials() takes 0 positional arguments but 1 was given
```

https://github.com/maptiler/qgis-maptiler-plugin/blob/f60c3706ee10fb6189eccaf256a5ca4cb770b748/geocoder.py#L21

**Comment by lazaa32** [comment]
Hi @jd-foster,
thanks for your bug report. I already fixed that and I will do a new release this week with other bug fixes. It should be possible to upgrade the plugin to the latest version next week (from QGIS plugin menu.)
