### ISSUE TITLE
Geocoding globalLocale stackTrace

### ISSUE THREAD

**Issue by klokan** [maptiler/qgis-maptiler-plugin#87]
On my computer:
```
Traceback (most recent call last):
  File "/home/petr.pridal/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin-master/geocoder.py", line 82, in on_searchword_returned
    geojson_dict = self._fetch_geocoding_api(searchword)
  File "/home/petr.pridal/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin-master/geocoder.py", line 112, in _fetch_geocoding_api
    locale = QSettings().value('locale/globalLocale')[0:2]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Kanahiro** [comment]
@klokan @lazaa32 
Assigned to @lazaa32 but I've fixed this issue because I have a time, please try this, thanks.

**Comment by lazaa32** [comment]
@kanahiro Thank you, I will test. Could you please have a look at #80? Thanks.
